// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenVSData
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenVSDataPackageString = "e646c8fe-8fab-4882-8e04-f8f909ebf8fe";
        public static Guid guidOpenVSDataPackage = new Guid(guidOpenVSDataPackageString);

        public const string guidOpenVSDataPackageCmdSetString = "43fa9acb-39b9-47ef-bced-179b129c8f5c";
        public static Guid guidOpenVSDataPackageCmdSet = new Guid(guidOpenVSDataPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenVSDataId = 0x0064;
    }
}