// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenVSData
{
    internal sealed partial class Vsix
    {
        public const string Id = "94b04aff-4627-4d39-ab5e-0175f201af64";
        public const string Name = "Open VS Data";
        public const string Description = @"Adds a menu command that lets you open the data storage folder of your current VS instance.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Maria Solano";
        public const string Tags = "storage, data, local";
    }
}
